# Generated by Django 2.1 on 2018-08-16 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180816_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=128, verbose_name='识别码')),
                ('trigger_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='时间')),
                ('describe', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftorigin', to=settings.AUTH_USER_MODEL, verbose_name='发送人员')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftuser', to=settings.AUTH_USER_MODEL, verbose_name='通知人员')),
            ],
        ),
    ]
