# Generated by Django 2.0.7 on 2018-08-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20180820_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.SmallIntegerField(choices=[(0, 'system'), (1, 'user'), (2, 'event'), (3, 'email'), (4, 'notification'), (5, 'other')], default=0, verbose_name='类型'),
        ),
    ]
