# Generated by Django 2.0.7 on 2018-08-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlabel',
            name='code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='icon Code'),
        ),
    ]
