# Generated by Django 2.0.7 on 2018-08-24 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_customlabel_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlabel',
            name='priority',
            field=models.IntegerField(default=1, unique=True, verbose_name='优先级'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumename',
            name='md5',
            field=models.CharField(default=2, max_length=128, verbose_name='MD5'),
            preserve_default=False,
        ),
    ]
